name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of deployment operation
        value: ${{jobs.deploy.outputs.outcome}}
    # secrets:
    #   some-secret:
    #     required: false

jobs:
  deploy:
    outputs:
      result: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: List contents
        run: ls -l
      - name: Output information
        run: echo "Deploying and uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result='success'" >> $GITHUB_OUTPUT